package com.ggumtak.readeraplus.reader

import org.junit.Assert.*
import org.junit.Test
import com.ggumtak.readeraplus.format.DocPosition

class ReaderJumpTest {
 @Test fun sanitizeRejectsBadCoordinatesAndFractions() { assertNull(ReaderJump.sanitize(-1,0,-1,.2f,null,null));assertNull(ReaderJump.sanitize(0,-1,-1,.2f,null,null));for (f in listOf(Float.NaN,Float.POSITIVE_INFINITY,1.1f,-2f)) assertNull(ReaderJump.sanitize(0,0,-1,f,null,null));val j=ReaderJump.sanitize(2,10,5,.5f,"sig","가".repeat(100))!!;assertEquals(-1,j.end);assertEquals(64,j.anchor.length);assertEquals(2,j.section) }
 @Test fun resolveCoordinatesAndFallbacks() { val fallback={f:Float->DocPosition(7,(f*100).toInt())};val j=ReaderJump(2,20,frac=.5f,sig="x");assertEquals(DocPosition(2,20),ReaderJump.resolve(j,"x",8,fallback));assertEquals(DocPosition(7,50),ReaderJump.resolve(j,"y",8,fallback));assertEquals(DocPosition(7,50),ReaderJump.resolve(j.copy(section=99),"x",8,fallback));assertNull(ReaderJump.resolve(j.copy(section=99,frac=-1f),"x",8,fallback));assertEquals(DocPosition(2,20),ReaderJump.resolve(j.copy(sig=""),"y",8,fallback)) }
 @Test fun anchorIgnoresWhitespaceAndObjectMarkers() { assertTrue(JumpAnchor.matches("가 \n나￼다",0,"가나다"));assertFalse(JumpAnchor.matches("가나다",0,"가너다"));assertTrue(JumpAnchor.matches("",0,""));assertFalse(JumpAnchor.matches("가",5,"가"));assertTrue(JumpAnchor.matches("가".repeat(24)+"나",0,"가".repeat(24)+"다")) }
 @Test fun fileSignatureIncludesSize() { assertEquals("e:12",NoteSig.of(null,12));assertEquals("txt:12",NoteSig.of("txt",12));assertNotEquals(NoteSig.of(null,12),NoteSig.of(null,13)) }
 @Test fun findSkipsWhitespaceAndReturnsTheFirstHit() { assertEquals(3,JumpAnchor.find("abc가 나다 가나다","가나다"));assertEquals(7,JumpAnchor.find("abc가나라 가나다","가나다",4));assertEquals(-1,JumpAnchor.find("가나라","가나다"));assertEquals(-1,JumpAnchor.find("가나다"," \n"));assertEquals(-1,JumpAnchor.find("","가"));assertEquals(1,JumpAnchor.find(" 가\n나","가나"));assertFalse(JumpAnchor.hasText(" \uFFFC\n"));assertTrue(JumpAnchor.hasText(" 가")) }
 @Test fun searchOrderGoesOutwardWithinTheBook() { assertArrayEquals(intArrayOf(5,6,4,7,3,8,2),JumpAnchor.searchOrder(5,9,7));assertArrayEquals(intArrayOf(0,1,2,3),JumpAnchor.searchOrder(0,4));assertArrayEquals(intArrayOf(3,2,1,0),JumpAnchor.searchOrder(3,4));assertArrayEquals(intArrayOf(),JumpAnchor.searchOrder(0,0));assertEquals(48,JumpAnchor.searchOrder(500,2000).size);assertArrayEquals(intArrayOf(2,1,0),JumpAnchor.searchOrder(9,3)) }
 @Test fun searchStopsAtTheFirstHitAndAtTheCaps() { val texts=Array(100){"본문 $it "+"가".repeat(10)};texts[57]="앞 노트의 문장";val loaded=ArrayList<Int>();val load={i:Int->loaded+=i;texts[i]}
  assertEquals(DocPosition(57,2),JumpAnchor.search(55,100,"노트의 문장",load));assertEquals(listOf(55,56,54,57),loaded)
  loaded.clear();assertNull(JumpAnchor.search(5,100,"노트의 문장",load));assertEquals(48,loaded.size)
  loaded.clear();assertNull(JumpAnchor.search(5,100,"노트의 문장",load,maxChars=30));assertEquals(2,loaded.size)
  var checks=0;assertNull(JumpAnchor.search(0,3,"없음",{null},{checks++}));assertEquals(3,checks) }
 @Test fun searchCheckCancels() { try { JumpAnchor.search(0,10,"x",{"y"},{throw IllegalStateException("cancelled")});fail() } catch (e: IllegalStateException) { assertEquals("cancelled",e.message) } }
 @Test fun quoteDrawnOnSigMatchOrWhenItsTextIsStillThere() { val text="첫 줄입니다. 인용한 문장이 여기에.";val at=text.indexOf("인용");assertTrue(JumpAnchor.quoteHolds("t:1","t:1","다른 글",0,"인용한 문장"));assertTrue(JumpAnchor.quoteHolds("","t:1",text,at,"인용한 문장"));assertTrue(JumpAnchor.quoteHolds("t:0","t:1",text,at,"인용한  문장"));assertFalse(JumpAnchor.quoteHolds("","t:1",text,at+1,"인용한 문장"));assertFalse(JumpAnchor.quoteHolds("t:0","t:1",text,0,"인용한 문장"));assertFalse(JumpAnchor.quoteHolds("","e:5",text,text.length+3,"인용")) }
 @Test fun epubSigMismatchFallsBackToTheFraction() { val locate={f:Float->DocPosition(4,(f*1000).toInt())};val now=NoteSig.of(null,2000);val j=ReaderJump(1,30,40,.25f,NoteSig.of(null,1999),"가나");assertEquals(DocPosition(4,250),ReaderJump.resolve(j,now,9,locate));assertEquals(DocPosition(1,30),ReaderJump.resolve(j.copy(sig=now),now,9,locate));assertEquals(DocPosition(1,30),ReaderJump.resolve(j.copy(sig=""),now,9,locate));assertEquals(DocPosition(1,30),ReaderJump.resolve(j.copy(frac=-1f),now,9,locate)) }
 @Test fun txtNoteSigFollowsTheTextSignature() { assertNotEquals(NoteSig.of("txt|p3|a",10),NoteSig.of("txt|p4|a",10));assertEquals(NoteSig.of("txt|p3|a",10),NoteSig.of("txt|p3|a",10)) }
 @Test fun chapterPlaceTextIsCleanedAndCapped() { assertEquals("",NotePlaceText.chapter(null));assertEquals("",NotePlaceText.chapter(" \n "));assertEquals("제 1 화 시작",NotePlaceText.chapter("  제 1\n\n화\t시작  "));assertEquals(200,NotePlaceText.chapter("가".repeat(300)).length);val spaced=NotePlaceText.chapter("가 ".repeat(150));assertTrue(spaced.length<=200);assertFalse(spaced.endsWith(" ")) }
 @Test fun epubAndLegacyQuotesFollowTheContentsDialogRule() { assertTrue(JumpAnchor.quoteHolds("","","다른 글",0,"인용"));assertFalse(JumpAnchor.quoteHolds("t:1","","다른 글",0,"인용"));assertTrue(JumpAnchor.quoteHolds("t:1","","인용 글",0,"인용"));assertFalse(JumpAnchor.quoteHolds("","t:1","",0,"")) }
}
