package com.ggumtak.readeraplus.render

import org.junit.Assert.*
import org.junit.Test
import com.ggumtak.readeraplus.data.DataLimits

class QuoteStylesTest {
 private fun lum(c:Int):Double { fun component(s:Int):Double { val v=((c ushr s) and 255)/255.0;return if(v<=.04045)v/12.92 else Math.pow((v+.055)/1.055,2.4) };return .2126*component(16)+.7152*component(8)+.0722*component(0) }
 @Test fun paletteIsReadableInBothSchemes() { for(s in 0..4) { assertTrue("day $s",(lum(QuoteStyles.colorFill(s,false))+.05)/.05>=8.0);assertTrue("night $s",1.05/(lum(QuoteStyles.colorFill(s,true))+.05)>=8.0) } }
 @Test fun nightColoursKeepTheLightTextOfMaruAndBlackPagesReadable() { val ddd=lum(0xFFDDDDDD.toInt());for(s in 0..4) assertTrue("night $s",(ddd+.05)/(lum(QuoteStyles.colorFill(s,true))+.05)>=5.5) }
 @Test fun dayColoursAreRidis() { assertEquals(listOf(0xFFE7D87C.toInt(),0xFFBED370.toInt(),0xFF7CB9C8.toInt(),0xFFD6959C.toInt(),0xFFBE93CC.toInt(),0),(0..5).map { QuoteStyles.colorFill(it,false) });assertEquals(0xFFE7D87C.toInt(),QuoteStyles.colorFill(QuoteStyles.YELLOW,false));assertEquals(0xFFBED370.toInt(),QuoteStyles.colorFill(QuoteStyles.GREEN,false));assertEquals(0xFF7CB9C8.toInt(),QuoteStyles.colorFill(QuoteStyles.BLUE,false));assertEquals(0xFFD6959C.toInt(),QuoteStyles.colorFill(QuoteStyles.RED,false));assertEquals(0xFFBE93CC.toInt(),QuoteStyles.colorFill(QuoteStyles.PURPLE,false)) }
 @Test fun nightColoursAreDarkOpaqueAndDistinct() { val night=(0..4).map { QuoteStyles.colorFill(it,true) };assertEquals(5,night.toSet().size);for(c in night) { assertEquals(0xFF,c ushr 24);assertTrue(lum(c)<.1) };assertEquals(0,QuoteStyles.colorFill(QuoteStyles.UNDERLINE,true)) }
 @Test fun idsStayAsStored() { assertEquals(listOf(0,1,2,3,4,5),listOf(QuoteStyles.YELLOW,QuoteStyles.GREEN,QuoteStyles.BLUE,QuoteStyles.RED,QuoteStyles.PURPLE,QuoteStyles.UNDERLINE));assertEquals(6,QuoteStyles.COUNT) }
 @Test fun paletteOrderIsRidis() { assertEquals(listOf(QuoteStyles.YELLOW,QuoteStyles.GREEN,QuoteStyles.PURPLE,QuoteStyles.BLUE,QuoteStyles.RED,QuoteStyles.UNDERLINE),(0 until QuoteStyles.COUNT).map { QuoteStyles.paletteStyle(it) });assertEquals(listOf("노랑","초록","보라","파랑","빨강","밑줄"),(0 until QuoteStyles.COUNT).map { QuoteStyles.label(QuoteStyles.paletteStyle(it)) }) }
 @Test fun paletteOrderIsAPermutationAndPositionIsItsInverse() { assertEquals((0 until QuoteStyles.COUNT).toSet(),(0 until QuoteStyles.COUNT).map { QuoteStyles.paletteStyle(it) }.toSet());for(s in 0 until QuoteStyles.COUNT) { assertEquals(s,QuoteStyles.paletteStyle(QuoteStyles.palettePosition(s))) };assertEquals(QuoteStyles.palettePosition(QuoteStyles.YELLOW),QuoteStyles.palettePosition(99));assertEquals(QuoteStyles.YELLOW,QuoteStyles.paletteStyle(-1));assertEquals(QuoteStyles.YELLOW,QuoteStyles.paletteStyle(6));assertEquals(5,QuoteStyles.palettePosition(QuoteStyles.UNDERLINE)) }
 @Test fun underlineAccentIsRed() { val c=QuoteStyles.UNDERLINE_ACCENT;assertEquals(0xFF,c ushr 24);assertTrue(((c shr 16) and 255)>200&&((c shr 8) and 255)<110&&(c and 255)<110) }
 @Test fun selectionColoursAreRidisBlue() { assertEquals(0xFF99C9F0.toInt(),SelectionColors.fill(false));assertEquals(0xFF1F8CE6.toInt(),SelectionColors.handle(false));assertNotEquals(SelectionColors.fill(false),SelectionColors.fill(true));assertNotEquals(SelectionColors.handle(false),SelectionColors.handle(true)) }
 @Test fun selectionFillKeepsTheTextReadable() { assertTrue((lum(SelectionColors.fill(false))+.05)/.05>=8.0);assertTrue(1.05/(lum(SelectionColors.fill(true))+.05)>=5.0);assertTrue((lum(0xFFDDDDDD.toInt())+.05)/(lum(SelectionColors.fill(true))+.05)>=4.5) }
 @Test fun exactInkLevelsAndDistinctMarks() { for(s in 0 until QuoteStyles.COUNT) { val g=QuoteStyles.inkGrey(s);assertTrue(g<0 || g in 0xBB..0xEE && g%0x11==0);assertTrue(QuoteStyles.thumbGrey(s)>=0);for(t in 0 until s) assertTrue(g!=QuoteStyles.inkGrey(t) || QuoteStyles.inkLine(s)!=QuoteStyles.inkLine(t)) };assertEquals(DataLimits.QUOTE_STYLE_MAX,QuoteStyles.MAX_STORED) }
 @Test fun stableIdsAndKoreanNames() { assertEquals(0,QuoteStyles.of(15));assertEquals(0,QuoteStyles.of(-1));assertEquals(listOf("노랑","초록","파랑","빨강","보라","밑줄"),(0..5).map { QuoteStyles.label(it) });assertEquals("[초록]",QuoteStyles.tag(1));assertEquals(0,QuoteStyles.colorFill(5,false)) }
}
